# Multidimensional array computing

The principles is `Python` may be slow so `numpy` implements all in `C` and interfaces with `Python`

In [1]:
import random
import numpy as np 

In [2]:
n = 100000
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [3]:
x[:3]

[0.46552173222988447, 0.4822502787843759, 0.6610346128469697]

In [4]:
y[:3]

[0.9574325108099967, 0.19273329618620094, 0.9344910579983424]

In [6]:
z = [x[i]+y[i] for i in range(n)]
z[:3]

[1.4229542430398812, 0.6749835749705768, 1.595525670845312]

In [8]:
z = [a + b for a, b in zip(x,y)]
z[:3]

[1.4229542430398812, 0.6749835749705768, 1.595525670845312]

In [9]:
%timeit [a + b for a, b in zip(x,y)]

11.6 ms ± 635 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Now let's compare with `numpy`

In [10]:
xa = np.array(x)
ya = np.array(y)
xa[:3]

array([ 0.46552173,  0.48225028,  0.66103461])

In [12]:
za = xa + ya
za[:3]

array([ 1.42295424,  0.67498357,  1.59552567])

In [13]:
%timeit xa+ya

295 µs ± 24.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


As it can be seen `numpy` is much faster!

In [14]:
%timeit sum(x)

656 µs ± 16.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [27]:
%timeit np.sum(xa)

62.5 µs ± 4.89 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


`Numpy` is faster!

In [23]:
d = [abs(x[i]-y[j]) for i in range(1000) for j in range(1000)]
d[:3]

[0.49191077858011223, 0.2727884360436835, 0.46896932576845796]

In [25]:
%timeit [abs(x[i]-y[j]) for i in range(1000) for j in range(1000)]

278 ms ± 24.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [26]:
%timeit np.abs(xa[:1000, np.newaxis] - ya[:1000])

8.11 ms ± 110 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Again `numpy` has won! 

In [29]:
np.array([1, 2, 3]) * np.array([1, 2, 3])

array([1, 4, 9])

In [30]:
np.__version__

'1.13.3'

In [34]:
xa[:3].shape

(3,)

In [35]:
xa[:3,np.newaxis].shape

(3, 1)